theme = "one-half-teddy"

[editor]
true-color = true
cursorline = true
scrolloff = 8
auto-pairs = false
auto-format = false

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner" ]
center = [ "file-name", "version-control"]

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = false
display-messages = false
auto-signature-help = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

C-s = ":w"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "move_line_up", "paste_after"]

y = "yank_to_clipboard"
p = "paste_clipboard_before"
R = "replace_selections_with_clipboard"
      
[keys.select]
y = "yank_to_clipboard"
p = "paste_clipboard_before"
R = "replace_selections_with_clipboard"

[keys.insert]
C-space = "signature_help"
